name = "jejaknasab-v2"
compatibility_date = "2026-08-26"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "jejaknasab-db"
database_id = "ddf3a0a8-a1db-41d0-a066-d3551a604a73"
