const E=new TextEncoder(),D=new TextDecoder();
const J=(d,s=200,h={})=>new Response(JSON.stringify(d),{status:s,headers:{'content-type':'application/json;charset=utf-8',...h}});
const B=(m,s=400)=>J({error:m},s);
const clean=(x,n=5000)=>String(x??'').trim().slice(0,n),mail=x=>String(x??'').trim().toLowerCase();
const b64=b=>btoa(String.fromCharCode(...new Uint8Array(b))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
const ub=s=>{s=s.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';return Uint8Array.from(atob(s),c=>c.charCodeAt(0))};
const rand=()=>b64(crypto.getRandomValues(new Uint8Array(24)));
const shortRand=()=>b64(crypto.getRandomValues(new Uint8Array(4)));

async function uniqueShortToken(env){for(let i=0;i<8;i++){const t=shortRand();if(!await env.DB.prepare('SELECT id FROM share_tokens WHERE token=?').bind(t).first())return t}return shortRand()}
async function hmac(sec,data){const k=await crypto.subtle.importKey('raw',E.encode(sec),{name:'HMAC',hash:'SHA-256'},false,['sign']);return b64(await crypto.subtle.sign('HMAC',k,E.encode(data)))}
async function makeTok(sec,p){const x=b64(E.encode(JSON.stringify(p)));return x+'.'+await hmac(sec,x)}
async function readTok(sec,t){if(!sec||!t)return null;const [x,s]=t.split('.');if(!x||!s)return null;try{if((await hmac(sec,x))!==s)return null;const p=JSON.parse(D.decode(ub(x)));return p.exp>Date.now()?p:null}catch{return null}}
async function phash(p,s){s=s?ub(s):crypto.getRandomValues(new Uint8Array(16));const k=await crypto.subtle.importKey('raw',E.encode(p),'PBKDF2',false,['deriveBits']);const z=await crypto.subtle.deriveBits({name:'PBKDF2',salt:s,iterations:100000,hash:'SHA-256'},k,256);return{hash:b64(z),salt:b64(s)}}
const cookie=(v,max=604800)=>`jn_session=${v}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${max}`;
async function body(r){try{return await r.json()}catch{return{}}}
async function userOf(env,req){const raw=req.headers.get('Cookie')?.match(/(?:^|;\s*)jn_session=([^;]+)/)?.[1];const t=await readTok(env.SESSION_SECRET,raw);if(!t)return null;return env.DB.prepare('SELECT id,name,email,role,status FROM users WHERE id=?').bind(t.uid).first()}
async function planOf(env,uid){try{const r=await env.DB.prepare('SELECT plan FROM user_plans WHERE user_id=?').bind(uid).first();return r?.plan==='ultimate'?'ultimate':'premium'}catch{return'premium'}}
const limits=p=>p==='ultimate'?{gen:6,members:20}:{gen:3,members:10};
const price=(p,e)=>p==='ultimate'?Number(e.ULTIMATE_PRICE||100000):Number(e.PREMIUM_PRICE||50000);
const pname=p=>[p?.first_name,p?.last_name].filter(Boolean).join(' ');
const age=(b,d='')=>{if(!b)return null;const a=new Date(b+'T00:00:00'),z=d?new Date(d+'T00:00:00'):new Date();if(Number.isNaN(a.getTime())||Number.isNaN(z.getTime()))return null;let n=z.getFullYear()-a.getFullYear();if(z.getMonth()<a.getMonth()||(z.getMonth()===a.getMonth()&&z.getDate()<a.getDate()))n--;return n<0?null:n};
async function tree(env,id){return env.DB.prepare('SELECT * FROM family_trees WHERE id=?').bind(id).first()}
async function refreshAutoTreeName(env,tid){const t=await tree(env,tid);if(!t||!Number(t.auto_name))return;const r=await env.DB.prepare("SELECT p.* FROM persons p WHERE p.tree_id=? AND p.gender='male' AND NOT EXISTS(SELECT 1 FROM relationships r WHERE r.tree_id=p.tree_id AND r.to_person_id=p.id AND r.type='parent') ORDER BY CASE WHEN p.birth_date='' THEN 1 ELSE 0 END,p.birth_date,p.id LIMIT 1").bind(tid).first();const n=r?pname(r):'Silsilah Keluarga';await env.DB.prepare('UPDATE family_trees SET name=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(n,tid).run()}
async function graph(env,tid){const ps=(await env.DB.prepare('SELECT * FROM persons WHERE tree_id=?').bind(tid).all()).results||[],rs=(await env.DB.prepare('SELECT * FROM relationships WHERE tree_id=?').bind(tid).all()).results||[];const pa=new Map(),ch=new Map(),sp=new Map();const add=(m,k,v)=>{if(!m.has(k))m.set(k,[]);m.get(k).push(v)};for(const r of rs){if(r.type==='parent'){add(pa,r.to_person_id,r.from_person_id);add(ch,r.from_person_id,r.to_person_id)}else{add(sp,r.from_person_id,r.to_person_id);add(sp,r.to_person_id,r.from_person_id)}}return{ps,rs,pa,ch,sp}}
function walk(start,map,n){const o=new Map([[start,0]]),q=[[start,0]];while(q.length){const[x,d]=q.shift();if(d>=n)continue;for(const y of map.get(x)||[])if(!o.has(y)){o.set(y,d+1);q.push([y,d+1])}}return o}
function siblings(start,g){const s=new Set();for(const p of g.pa.get(start)||[])for(const c of g.ch.get(p)||[])if(c!==start)s.add(c);return s}

function generationMap(start,g,n){const dist=new Map([[start,0]]),q=[start];while(q.length){const x=q.shift(),d=dist.get(x);if(Math.abs(d)>n)continue;for(const y of g.pa.get(x)||[])if(!dist.has(y)){dist.set(y,d-1);q.push(y)}for(const y of g.ch.get(x)||[])if(!dist.has(y)){dist.set(y,d+1);q.push(y)}for(const y of g.sp.get(x)||[])if(!dist.has(y)){dist.set(y,d);q.push(y)}for(const par of g.pa.get(x)||[])for(const sib of g.ch.get(par)||[])if(!dist.has(sib)){dist.set(sib,d);q.push(sib)}}return dist}
function memberScope(start,g,n){const ids=new Set([start]);for(const x of walk(start,g.pa,n).keys())ids.add(x);for(const x of walk(start,g.ch,n).keys())ids.add(x);const ss=siblings(start,g);for(const x of ss)ids.add(x);for(const x of ss)for(const y of walk(x,g.ch,n).keys())ids.add(y);for(const x of ss)for(const y of g.sp.get(x)||[])ids.add(y);for(const x of g.sp.get(start)||[]){ids.add(x);for(const y of walk(x,g.ch,n).keys())ids.add(y)}for(const x of [...ids])for(const y of g.sp.get(x)||[])ids.add(y);return ids}
async function membership(env,tid,uid){return env.DB.prepare("SELECT tm.*,p.first_name,p.last_name FROM tree_members tm JOIN persons p ON p.id=tm.person_id WHERE tm.tree_id=? AND tm.user_id=? AND tm.status='active'").bind(tid,uid).first()}
async function audit(env,tid,uid,a,t,id,details=''){try{await env.DB.prepare('INSERT INTO audit_logs(tree_id,actor_user_id,action,entity_type,entity_id,details) VALUES(?,?,?,?,?,?)').bind(tid,uid,a,t,id||null,details).run()}catch{}}
async function ownerAccess(u,t){return u?.role==='member'&&t.created_by===u.id}
async function scoped(env,u,t){if(u.role!=='member'||t.created_by===u.id)return null;const m=await membership(env,t.id,u.id);if(!m)return null;const g=await graph(env,t.id),p=await planOf(env,u.id);return{m,g,ids:memberScope(m.person_id,g,limits(p).gen),plan:p,planGen:limits(p).gen}}
async function ensureExtras(env){
 const stmts=[
 "CREATE TABLE IF NOT EXISTS user_plans (user_id INTEGER PRIMARY KEY, plan TEXT NOT NULL CHECK(plan IN ('premium','ultimate')) DEFAULT 'premium', created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE)",
 "CREATE TABLE IF NOT EXISTS person_privacy (person_id INTEGER PRIMARY KEY, show_name INTEGER NOT NULL DEFAULT 1, show_age INTEGER NOT NULL DEFAULT 1, show_birth_date INTEGER NOT NULL DEFAULT 0, show_birth_place INTEGER NOT NULL DEFAULT 0, show_photo INTEGER NOT NULL DEFAULT 0, show_notes INTEGER NOT NULL DEFAULT 0, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(person_id) REFERENCES persons(id) ON DELETE CASCADE)",
 "CREATE TABLE IF NOT EXISTS tree_members (id INTEGER PRIMARY KEY AUTOINCREMENT, tree_id INTEGER NOT NULL, user_id INTEGER NOT NULL, person_id INTEGER NOT NULL, role TEXT NOT NULL DEFAULT 'member', status TEXT NOT NULL DEFAULT 'invited', created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(tree_id,user_id), UNIQUE(tree_id,person_id), FOREIGN KEY(tree_id) REFERENCES family_trees(id) ON DELETE CASCADE, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE, FOREIGN KEY(person_id) REFERENCES persons(id) ON DELETE CASCADE)",
 "CREATE TABLE IF NOT EXISTS invitations (id INTEGER PRIMARY KEY AUTOINCREMENT, tree_id INTEGER NOT NULL, person_id INTEGER NOT NULL, invited_email TEXT NOT NULL DEFAULT '', invited_phone TEXT DEFAULT '', invited_by INTEGER NOT NULL, requester_id INTEGER, token TEXT NOT NULL UNIQUE, status TEXT NOT NULL DEFAULT 'pending', created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, responded_at TEXT DEFAULT '', requested_at TEXT DEFAULT '', FOREIGN KEY(tree_id) REFERENCES family_trees(id) ON DELETE CASCADE, FOREIGN KEY(person_id) REFERENCES persons(id) ON DELETE CASCADE, FOREIGN KEY(invited_by) REFERENCES users(id) ON DELETE CASCADE)",
 "CREATE TABLE IF NOT EXISTS claim_requests (id INTEGER PRIMARY KEY AUTOINCREMENT, tree_id INTEGER NOT NULL, person_id INTEGER NOT NULL, requester_id INTEGER NOT NULL, note TEXT DEFAULT '', status TEXT NOT NULL DEFAULT 'pending', created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, reviewed_at TEXT DEFAULT '', FOREIGN KEY(tree_id) REFERENCES family_trees(id) ON DELETE CASCADE, FOREIGN KEY(person_id) REFERENCES persons(id) ON DELETE CASCADE, FOREIGN KEY(requester_id) REFERENCES users(id) ON DELETE CASCADE)",
 "CREATE TABLE IF NOT EXISTS share_tokens (id INTEGER PRIMARY KEY AUTOINCREMENT, tree_id INTEGER NOT NULL UNIQUE, token TEXT NOT NULL UNIQUE, is_public INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(tree_id) REFERENCES family_trees(id) ON DELETE CASCADE)",
 "CREATE TABLE IF NOT EXISTS audit_logs (id INTEGER PRIMARY KEY AUTOINCREMENT, tree_id INTEGER NOT NULL, actor_user_id INTEGER NOT NULL, action TEXT NOT NULL, entity_type TEXT NOT NULL, entity_id INTEGER, details TEXT DEFAULT '', created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(tree_id) REFERENCES family_trees(id) ON DELETE CASCADE)"
 ];
 try{await env.DB.batch(stmts.map(x=>env.DB.prepare(x)));try{await env.DB.prepare("ALTER TABLE family_trees ADD COLUMN auto_name INTEGER NOT NULL DEFAULT 0").run()}catch{};try{await env.DB.prepare("ALTER TABLE person_privacy ADD COLUMN show_notes INTEGER NOT NULL DEFAULT 0").run()}catch{};try{await env.DB.prepare("ALTER TABLE persons ADD COLUMN sibling_order INTEGER NOT NULL DEFAULT 0").run()}catch{};for(const q of ["ALTER TABLE invitations ADD COLUMN invited_phone TEXT DEFAULT ''","ALTER TABLE invitations ADD COLUMN requester_id INTEGER","ALTER TABLE invitations ADD COLUMN requested_at TEXT DEFAULT ''"]){try{await env.DB.prepare(q).run()}catch{}}try{await env.DB.prepare("CREATE INDEX IF NOT EXISTS idx_persons_tree_order ON persons(tree_id,sibling_order,id)").run()}catch{};await env.DB.prepare("INSERT OR IGNORE INTO user_plans(user_id,plan) SELECT id,'premium' FROM users WHERE role='member'").run();await env.DB.prepare("INSERT OR IGNORE INTO person_privacy(person_id) SELECT id FROM persons").run()}catch(e){/* existing schema may already be complete */}
}

export async function onRequest({request,env}){
 if(!env.DB)return B('D1 binding DB belum dikonfigurasi.',500);
 await ensureExtras(env);
 const url=new URL(request.url);let path=url.pathname.replace(/^\/api(?=\/|$)/,'').replace(/\/$/,'')||'/';const m=request.method;
 if(path==='/setup-owner'&&m==='POST'){
  if(!env.OWNER_SETUP_KEY)return B('OWNER_SETUP_KEY belum dikonfigurasi di Cloudflare.',500);const b=await body(request);if(b.setupKey!==env.OWNER_SETUP_KEY)return B('Setup key salah.',403);const c=await env.DB.prepare("SELECT COUNT(*) n FROM users WHERE role='owner'").first();if(Number(c?.n))return B('Owner sudah dibuat.',409);const n=clean(b.name,120),e=mail(b.email),pw=String(b.password||'');if(n.length<2||!e.includes('@')||pw.length<8)return B('Data owner tidak valid. Password minimal 8 karakter.');const p=await phash(pw);await env.DB.prepare("INSERT INTO users(name,email,password_hash,password_salt,role,status) VALUES(?,?,?,?,'owner','active')").bind(n,e,p.hash,p.salt).run();return J({ok:true,message:'Owner berhasil dibuat. Silakan login.'})
 }
 if(path==='/config'&&m==='GET')return J({premium:{price:price('premium',env),familyMembers:10,generation:3},ultimate:{price:price('ultimate',env),familyMembers:20,generation:6,upgradePrice:Math.round(price('ultimate',env)*0.6)},upgradeDiscount:40,paymentInstructions:env.PAYMENT_INSTRUCTIONS||'Hubungi owner untuk instruksi pembayaran.'});
 const pub=path.match(/^\/public\/trees\/([A-Za-z0-9_-]+)$/);if(pub&&m==='GET'){
  const st=await env.DB.prepare('SELECT * FROM share_tokens WHERE token=? AND is_public=1').bind(pub[1]).first();if(!st)return B('Silsilah publik tidak ditemukan.',404);const t=await tree(env,st.tree_id);if(!t)return B('Silsilah tidak ditemukan.',404);const g=await graph(env,t.id);const pr=(await env.DB.prepare('SELECT * FROM person_privacy WHERE person_id IN (SELECT id FROM persons WHERE tree_id=?)').bind(t.id).all()).results||[],pp=new Map(pr.map(x=>[x.person_id,x]));const persons=g.ps.map(p=>{const v=pp.get(p.id)||{show_name:1,show_age:1,show_birth_date:0,show_birth_place:0,show_photo:0};const x={id:p.id,name:v.show_name?pname(p):'Anggota keluarga',gender:p.gender,isDeceased:!!p.death_date,age:v.show_age?age(p.birth_date,p.death_date):null,sibling_order:Number(p.sibling_order||0)};if(v.show_birth_date)x.birth_date=p.birth_date||'';if(v.show_birth_place)x.birth_place=p.birth_place||'';if(v.show_photo)x.photo_url=p.photo_url||'';if(v.show_notes)x.notes=p.notes||'';if(p.death_date)x.death_date=p.death_date;return x});return J({tree:{id:t.id,name:t.name,description:t.description},persons,relationships:g.rs},200,{'Cache-Control':'no-store, no-cache, must-revalidate'})
 }
 const ivg=path.match(/^\/invite\/([A-Za-z0-9_-]+)$/);if(ivg&&m==='GET'){const i=await env.DB.prepare("SELECT i.*,t.name tree_name,p.first_name,p.last_name FROM invitations i JOIN family_trees t ON t.id=i.tree_id JOIN persons p ON p.id=i.person_id WHERE i.token=? AND i.status='pending'").bind(ivg[1]).first();if(!i)return B('Undangan tidak ditemukan atau sudah digunakan.',404);return J({token:i.token,treeName:i.tree_name,personName:pname(i),invitedEmail:i.invited_email||'',invitedPhone:i.invited_phone||'',requested:!!i.requested_at})}
 if(!env.SESSION_SECRET)return B('SESSION_SECRET belum dikonfigurasi.',500);
 const u=await userOf(env,request);
 if(path==='/me'&&m==='GET')return J({user:u?{...u,plan:u.role==='member'?await planOf(env,u.id):null}:null});
 if(path==='/register'&&m==='POST'){
  const b=await body(request),n=clean(b.name,120),e=mail(b.email),pw=String(b.password||''),p=b.plan==='ultimate'?'ultimate':'premium',inviteToken=clean(b.inviteToken,200);if(n.length<2||!e.includes('@')||pw.length<8)return B('Nama, email valid, dan password minimal 8 karakter wajib diisi.');if(await env.DB.prepare('SELECT id FROM users WHERE email=?').bind(e).first())return B('Email sudah terdaftar.',409);if(inviteToken){const inv=await env.DB.prepare("SELECT id,invited_email FROM invitations WHERE token=? AND status='pending'").bind(inviteToken).first();if(!inv)return B('Link undangan tidak valid atau sudah tidak berlaku.',404);if(inv.invited_email&&mail(inv.invited_email)!==e)return B('Email pendaftaran harus sama dengan email undangan.',400)}const h=await phash(pw);const r=await env.DB.prepare("INSERT INTO users(name,email,password_hash,password_salt,role,status) VALUES(?,?,?,?, 'member','pending')").bind(n,e,h.hash,h.salt).run();const id=r.meta.last_row_id;await env.DB.prepare('INSERT OR REPLACE INTO user_plans(user_id,plan) VALUES(?,?)').bind(id,p).run();await env.DB.prepare('INSERT INTO payment_requests(user_id,amount,status,note) VALUES(?,?,\'pending\',?)').bind(id,price(p,env),`Paket ${p}`).run();if(inviteToken){const inv=await env.DB.prepare("SELECT id FROM invitations WHERE token=? AND status='pending'").bind(inviteToken).first();if(inv)await env.DB.prepare('UPDATE invitations SET requester_id=?,requested_at=CURRENT_TIMESTAMP WHERE id=? AND status=\'pending\'').bind(id,inv.id).run()}return J({ok:true,message:inviteToken?`Pendaftaran ${p} berhasil. Permintaan Family Member sudah dikirim dan menunggu persetujuan Owner Akun.`:`Pendaftaran ${p} berhasil. Lakukan pembayaran dan tunggu aktivasi Owner.`},201)
 }
 if(path==='/login'&&m==='POST'){
  const b=await body(request),e=mail(b.email),pw=String(b.password||''),x=await env.DB.prepare('SELECT * FROM users WHERE email=?').bind(e).first();if(!x||(await phash(pw,x.password_salt)).hash!==x.password_hash)return B('Email atau password salah.',401);if(x.status!=='active')return B(x.status==='pending'?'Akun belum aktif. Tunggu aktivasi setelah pembayaran.':'Akun ditangguhkan.',403);const tok=await makeTok(env.SESSION_SECRET,{uid:x.id,role:x.role,exp:Date.now()+604800000});return J({ok:true,user:{id:x.id,name:x.name,email:x.email,role:x.role,plan:x.role==='member'?await planOf(env,x.id):null}},200,{'Set-Cookie':cookie(tok)})
 }
 if(path==='/logout'&&m==='POST')return J({ok:true},200,{'Set-Cookie':cookie('',0)});
 if(!u)return B('Login diperlukan.',401);
 if(path==='/owner/users'&&m==='GET'){
  if(u.role!=='owner')return B('Akses Owner Web diperlukan.',403);const r=await env.DB.prepare(`SELECT u.id,u.name,u.email,u.status,u.created_at,COALESCE(up.plan,'premium') plan,COALESCE((SELECT p.status FROM payment_requests p WHERE p.user_id=u.id ORDER BY p.id DESC LIMIT 1),'none') payment_status,COALESCE((SELECT p.amount FROM payment_requests p WHERE p.user_id=u.id ORDER BY p.id DESC LIMIT 1),0) amount,COALESCE((SELECT p.note FROM payment_requests p WHERE p.user_id=u.id ORDER BY p.id DESC LIMIT 1),'') payment_note FROM users u LEFT JOIN user_plans up ON up.user_id=u.id WHERE u.role='member' ORDER BY u.created_at DESC`).all();return J({users:r.results||[]})
 }
 if(/^\/owner\/users\/(activate|suspend)$/.test(path)&&m==='POST'){
  if(u.role!=='owner')return B('Akses Owner Web diperlukan.',403);const b=await body(request),id=Number(b.userId);if(path.endsWith('activate')){await env.DB.prepare("UPDATE users SET status='active',updated_at=CURRENT_TIMESTAMP WHERE id=? AND role='member'").bind(id).run();const latest=await env.DB.prepare("SELECT id,note FROM payment_requests WHERE user_id=? ORDER BY id DESC LIMIT 1").bind(id).first();await env.DB.prepare("UPDATE payment_requests SET status='paid',reviewed_at=CURRENT_TIMESTAMP WHERE user_id=? AND id=(SELECT id FROM payment_requests WHERE user_id=? ORDER BY id DESC LIMIT 1)").bind(id,id).run();if(latest?.note?.toLowerCase().includes('upgrade premium ke ultimate'))await env.DB.prepare("UPDATE user_plans SET plan='ultimate',updated_at=CURRENT_TIMESTAMP WHERE user_id=?").bind(id).run()}else await env.DB.prepare("UPDATE users SET status='suspended',updated_at=CURRENT_TIMESTAMP WHERE id=? AND role='member'").bind(id).run();return J({ok:true})
 }
 if(path==='/trees'&&m==='GET'){
  if(u.role==='owner'){const r=await env.DB.prepare('SELECT t.*,u.name creator_name FROM family_trees t JOIN users u ON u.id=t.created_by ORDER BY t.updated_at DESC').all();return J({trees:r.results||[],readonly:true})}
  const r=await env.DB.prepare("SELECT t.*,u.name creator_name FROM family_trees t JOIN users u ON u.id=t.created_by WHERE t.created_by=? OR EXISTS(SELECT 1 FROM tree_members tm WHERE tm.tree_id=t.id AND tm.user_id=? AND tm.status='active') ORDER BY t.updated_at DESC").bind(u.id,u.id).all();return J({trees:r.results||[],readonly:false})
 }
 if(path==='/trees'&&m==='POST'){
  if(u.role!=='member')return B('Owner Web tidak dapat membuat pohon pelanggan.',403);
  const b=await body(request),auto=!!b.autoName,n=clean(b.name,150);if(!auto&&!n)return B('Nama silsilah wajib diisi.');
  const existing=await env.DB.prepare('SELECT id FROM family_trees WHERE created_by=? LIMIT 1').bind(u.id).first();
  if(existing)return B('Akun Anda sudah memiliki satu silsilah. Satu Owner Akun hanya dapat membuat satu silsilah.',409);
  const r=await env.DB.prepare('INSERT INTO family_trees(name,description,created_by,auto_name) VALUES(?,?,?,?)').bind(auto?'Silsilah Keluarga':n,clean(b.description,1000),u.id,auto?1:0).run();await refreshAutoTreeName(env,r.meta.last_row_id);return J({id:r.meta.last_row_id},201)
 }
 const td=path.match(/^\/trees\/(\d+)$/);if(td&&m==='PATCH'){const t=await tree(env,Number(td[1]));if(!t||u.role!=='member'||t.created_by!==u.id)return B('Hanya Owner Akun yang dapat mengubah nama silsilah.',403);const b=await body(request),auto=!!b.autoName,n=clean(b.name,150);if(!auto&&!n)return B('Nama silsilah wajib diisi.');await env.DB.prepare('UPDATE family_trees SET name=?,auto_name=?,description=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(auto?'Silsilah Keluarga':n,auto?1:0,clean(b.description,1000),t.id).run();if(auto)await refreshAutoTreeName(env,t.id);const nt=await tree(env,t.id);return J({ok:true,name:nt?.name||n,autoName:auto})}if(td&&m==='DELETE'){const t=await tree(env,Number(td[1]));if(!t)return B('Silsilah tidak ditemukan.',404);if(!(await ownerAccess(u,t)))return B('Hanya Owner Akun yang dapat menghapus silsilah.',403);await env.DB.prepare('DELETE FROM family_trees WHERE id=?').bind(t.id).run();return J({ok:true})}
 const tp=path.match(/^\/trees\/(\d+)\/persons$/);if(tp){
  const tid=Number(tp[1]),t=await tree(env,tid);if(!t)return B('Silsilah tidak ditemukan.',404);
  if(m==='GET'){let ok=false;if(u.role==='owner'||t.created_by===u.id||await membership(env,tid,u.id))ok=true;if(!ok)return B('Tidak memiliki akses.',403);let canEdit=new Set();if(t.created_by===u.id){for(const x of (await env.DB.prepare('SELECT id FROM persons WHERE tree_id=?').bind(tid).all()).results||[])canEdit.add(x.id)}else if(u.role==='member'){const sc=await scoped(env,u,t);if(sc)for(const x of sc.ids)canEdit.add(x)}const r=await env.DB.prepare('SELECT p.*,pp.show_name,pp.show_age,pp.show_birth_date,pp.show_birth_place,pp.show_photo,pp.show_notes FROM persons p LEFT JOIN person_privacy pp ON pp.person_id=p.id WHERE p.tree_id=? ORDER BY p.sibling_order,p.first_name,p.last_name,p.id').bind(tid).all();return J({persons:(r.results||[]).map(x=>({...x,can_edit:canEdit.has(x.id)})),readonly:u.role==='owner'})}
  if(m==='POST'){
   if(u.role==='owner')return B('Owner Web hanya memiliki akses baca.',403);const owner=t.created_by===u.id;const sc=owner?null:await scoped(env,u,t);if(!owner&&!sc)return B('Anda bukan Family Member pada pohon ini.',403);const b=await body(request),first=clean(b.first_name,100);if(!first)return B('Nama depan wajib.');const anchor=Number(b.anchor_person_id||0),rt=b.relation_type||'';if(!owner&&(!anchor||!sc.ids.has(anchor)))return B('Family Member hanya dapat menambah anggota di wilayah aksesnya.',403);if(anchor&&rt&&!['parent','spouse'].includes(rt))return B('Relasi tidak valid.');if(anchor&&rt==='parent'&&!owner){const gm=generationMap(sc.m.person_id,sc.g,sc.plan);const base=gm.get(anchor);if(base===undefined||!sc.ids.has(anchor))return B('Anggota tujuan berada di luar wilayah akses Anda.',403);const direction=b.parent_direction==='child_to_parent'?'up':'down';const next=Number(base)+(direction==='up'?-1:1);if(Math.abs(next)>sc.planGen)return B('Batas generasi paket Anda tercapai.',403)}const r=await env.DB.prepare('INSERT INTO persons(tree_id,first_name,last_name,gender,birth_date,death_date,birth_place,notes,photo_url) VALUES(?,?,?,?,?,?,?,?,?)').bind(tid,first,clean(b.last_name,100),['male','female','other'].includes(b.gender)?b.gender:'other',clean(b.birth_date,30),clean(b.death_date,30),clean(b.birth_place,200),clean(b.notes,3000),clean(b.photo_url,1000)).run();const pid=r.meta.last_row_id;await env.DB.prepare('INSERT OR IGNORE INTO person_privacy(person_id) VALUES(?)').bind(pid).run();if(anchor&&rt){let from=anchor,to=pid;if(rt==='parent'&&b.parent_direction==='child_to_parent'){from=pid;to=anchor}if(owner||sc.ids.has(anchor))await env.DB.prepare('INSERT OR IGNORE INTO relationships(tree_id,from_person_id,to_person_id,type) VALUES(?,?,?,?)').bind(tid,from,to,rt).run();if(rt==='parent'){const mx=await env.DB.prepare("SELECT COALESCE(MAX(p.sibling_order),0) n FROM persons p JOIN relationships r ON r.to_person_id=p.id WHERE r.tree_id=? AND r.from_person_id=? AND r.type='parent'").bind(tid,from).first();await env.DB.prepare('UPDATE persons SET sibling_order=? WHERE id=?').bind(Number(mx?.n||0)+1,pid).run()}}await env.DB.prepare('UPDATE family_trees SET updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(tid).run();await refreshAutoTreeName(env,tid);await audit(env,tid,u.id,'create','person',pid);return J({id:pid},201)
  }
 }
 const pd=path.match(/^\/persons\/(\d+)$/);if(pd){
  const pid=Number(pd[1]),p=await env.DB.prepare('SELECT p.*,t.created_by,t.id tree_id,t.name tree_name FROM persons p JOIN family_trees t ON t.id=p.tree_id WHERE p.id=?').bind(pid).first();if(!p)return B('Anggota tidak ditemukan.',404);const t=await tree(env,p.tree_id);
  if(m==='GET'){if(u.role==='owner'||t.created_by===u.id||await membership(env,p.tree_id,u.id))return J({person:p});return B('Tidak memiliki akses.',403)}
  if(m==='PATCH'){let ok=false;if(u.role==='member'&&t.created_by===u.id)ok=true;else if(u.role==='member'){const sc=await scoped(env,u,t);ok=!!sc?.ids.has(pid)}if(!ok)return B(u.role==='owner'?'Owner Web hanya memiliki akses baca.':'Anggota berada di luar wilayah akses Anda.',403);const b=await body(request);if(!clean(b.first_name,100))return B('Nama depan wajib.');await env.DB.prepare('UPDATE persons SET first_name=?,last_name=?,gender=?,birth_date=?,death_date=?,birth_place=?,notes=?,photo_url=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(clean(b.first_name,100),clean(b.last_name,100),['male','female','other'].includes(b.gender)?b.gender:'other',clean(b.birth_date,30),clean(b.death_date,30),clean(b.birth_place,200),clean(b.notes,3000),clean(b.photo_url,1000),pid).run();await env.DB.prepare('UPDATE family_trees SET updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(p.tree_id).run();await audit(env,p.tree_id,u.id,'update','person',pid);return J({ok:true})}
  if(m==='DELETE'){if(u.role!=='member'||t.created_by!==u.id)return B('Hanya Owner Akun yang dapat menghapus anggota.',403);await env.DB.prepare('DELETE FROM persons WHERE id=?').bind(pid).run();return J({ok:true})}
 }
 const tvp=path.match(/^\/trees\/(\d+)\/privacy$/);if(tvp&&(m==='GET'||m==='PATCH')){const tid=Number(tvp[1]),t=await tree(env,tid);if(!t||u.role!=='member'||t.created_by!==u.id)return B('Hanya Owner Akun yang dapat mengatur info publik.',403);if(m==='GET'){const x=await env.DB.prepare('SELECT show_name,show_age,show_birth_date,show_birth_place,show_photo,show_notes FROM person_privacy WHERE person_id IN (SELECT id FROM persons WHERE tree_id=?) ORDER BY person_id LIMIT 1').bind(tid).first();return J({privacy:x||{show_name:1,show_age:1,show_birth_date:0,show_birth_place:0,show_photo:0,show_notes:0}})}const b=await body(request);const vals=[b.show_name?1:0,b.show_age?1:0,b.show_birth_date?1:0,b.show_birth_place?1:0,b.show_photo?1:0,b.show_notes?1:0];const ids=(await env.DB.prepare('SELECT id FROM persons WHERE tree_id=?').bind(tid).all()).results||[];if(ids.length)await env.DB.batch(ids.map(x=>env.DB.prepare('INSERT OR REPLACE INTO person_privacy(person_id,show_name,show_age,show_birth_date,show_birth_place,show_photo,show_notes,updated_at) VALUES(?,?,?,?,?,?,?,CURRENT_TIMESTAMP)').bind(x.id,...vals)));return J({ok:true,count:ids.length})}
 const pv=path.match(/^\/persons\/(\d+)\/privacy$/);if(pv&&m==='GET'||pv&&m==='PATCH'){
  const p=await env.DB.prepare('SELECT p.*,t.created_by,t.id tree_id FROM persons p JOIN family_trees t ON t.id=p.tree_id WHERE p.id=?').bind(Number(pv[1])).first();if(!p)return B('Anggota tidak ditemukan.',404);if(u.role!=='member'||p.created_by!==u.id)return B('Hanya Owner Akun yang dapat mengubah privasi profil publik.',403);if(m==='GET'){const x=await env.DB.prepare('SELECT * FROM person_privacy WHERE person_id=?').bind(p.id).first();return J({privacy:x||{person_id:p.id,show_name:1,show_age:1,show_birth_date:0,show_birth_place:0,show_photo:0,show_notes:0}})}const b=await body(request);await env.DB.prepare('INSERT OR REPLACE INTO person_privacy(person_id,show_name,show_age,show_birth_date,show_birth_place,show_photo,show_notes,updated_at) VALUES(?,?,?,?,?,?,?,CURRENT_TIMESTAMP)').bind(p.id,b.show_name?1:0,b.show_age?1:0,b.show_birth_date?1:0,b.show_birth_place?1:0,b.show_photo?1:0,b.show_notes?1:0).run();return J({ok:true})
 }
 const rr=path.match(/^\/trees\/(\d+)\/relationships$/);if(rr){const tid=Number(rr[1]),t=await tree(env,tid);if(!t)return B('Silsilah tidak ditemukan.',404);if(m==='GET'){if(u.role==='owner'||t.created_by===u.id)return J({relationships:(await env.DB.prepare('SELECT * FROM relationships WHERE tree_id=? ORDER BY id').bind(tid).all()).results||[]});const sc=await scoped(env,u,t);if(!sc)return B('Tidak memiliki akses.',403);const all=(await env.DB.prepare('SELECT * FROM relationships WHERE tree_id=? ORDER BY id').bind(tid).all()).results||[];return J({relationships:all.filter(x=>sc.ids.has(x.from_person_id)&&sc.ids.has(x.to_person_id))})}if(m==='POST'){if(u.role!=='member')return B('Owner Web hanya memiliki akses baca.',403);const owner=t.created_by===u.id,sc=owner?null:await scoped(env,u,t);if(!owner&&!sc)return B('Tidak memiliki akses.',403);const b=await body(request),a=Number(b.from_person_id),z=Number(b.to_person_id),type=b.type;if(!a||!z||a===z||!['parent','spouse'].includes(type))return B('Relasi tidak valid.');if(!owner&&(!sc.ids.has(a)||!sc.ids.has(z)))return B('Relasi berada di luar wilayah akses Family Member.',403);const pa=await env.DB.prepare('SELECT id FROM persons WHERE id=? AND tree_id=?').bind(a,tid).first(),pz=await env.DB.prepare('SELECT id FROM persons WHERE id=? AND tree_id=?').bind(z,tid).first();if(!pa||!pz)return B('Anggota relasi tidak ditemukan.',404);await env.DB.prepare('INSERT OR IGNORE INTO relationships(tree_id,from_person_id,to_person_id,type) VALUES(?,?,?,?)').bind(tid,a,z,type).run();await refreshAutoTreeName(env,tid);await audit(env,tid,u.id,'create','relationship',null,`${type}:${a}->${z}`);return J({ok:true})}}
 const rd=path.match(/^\/relationships\/(\d+)$/);if(rd&&m==='DELETE'){const r=await env.DB.prepare('SELECT * FROM relationships WHERE id=?').bind(Number(rd[1])).first(),t=r&&await tree(env,r.tree_id);if(!r||!t)return B('Relasi tidak ditemukan.',404);if(u.role!=='member'||t.created_by!==u.id)return B('Hanya Owner Akun yang dapat menghapus relasi.',403);await env.DB.prepare('DELETE FROM relationships WHERE id=?').bind(r.id).run();await refreshAutoTreeName(env,t.id);return J({ok:true})}
 const co=path.match(/^\/trees\/(\d+)\/children-order$/);if(co&&m==='PATCH'){const tid=Number(co[1]),t=await tree(env,tid);if(!t)return B('Silsilah tidak ditemukan.',404);if(u.role!=='member')return B('Owner Web hanya memiliki akses baca.',403);const owner=t.created_by===u.id,sc=owner?null:await scoped(env,u,t);if(!owner&&!sc)return B('Tidak memiliki akses.',403);const b=await body(request),ids=Array.isArray(b.childIds)?b.childIds.map(Number).filter(Boolean):[],parentId=Number(b.parentId);if(!parentId||!ids.length)return B('Data urutan anak tidak valid.');if(!owner&&!sc.ids.has(parentId))return B('Orang tua berada di luar wilayah akses Anda.',403);const rows=(await env.DB.prepare("SELECT r.to_person_id,p.sibling_order FROM relationships r JOIN persons p ON p.id=r.to_person_id WHERE r.tree_id=? AND r.from_person_id=? AND r.type='parent' ORDER BY r.id").bind(tid,parentId).all()).results||[];const all=rows.map(x=>Number(x.to_person_id));const allowed=new Set(all);if(ids.some(x=>!allowed.has(x)))return B('Daftar anak tidak sesuai dengan relasi yang tersimpan.',400);if(!owner&&ids.some(x=>!sc.ids.has(x)))return B('Ada anak di luar wilayah akses Anda.',403);const ordered=owner?ids:[...all.filter(x=>!ids.includes(x)),...ids];await env.DB.batch(ordered.map((id,i)=>env.DB.prepare('UPDATE persons SET sibling_order=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND tree_id=?').bind(i+1,id,tid)));await env.DB.prepare('UPDATE family_trees SET updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(tid).run();await audit(env,tid,u.id,'reorder','children',parentId,ids.join(','));return J({ok:true,childIds:ids})}
 const sh=path.match(/^\/trees\/(\d+)\/share$/);if(sh){const t=await tree(env,Number(sh[1]));if(!t||u.role!=='member')return B('Akses Family Member diperlukan.',403);if(m==='GET'){if(t.created_by!==u.id&&!await membership(env,t.id,u.id))return B('Tidak memiliki akses.',403);let s=await env.DB.prepare('SELECT * FROM share_tokens WHERE tree_id=?').bind(t.id).first();if(s&&s.token.length>12&&t.created_by===u.id){const nt=await uniqueShortToken(env);await env.DB.prepare('UPDATE share_tokens SET token=?,updated_at=CURRENT_TIMESTAMP WHERE tree_id=?').bind(nt,t.id).run();s={...s,token:nt}}return J({public:!!s?.is_public,token:s?.token||null,url:s?.is_public?`${url.origin}/f/${s.token}`:null})}if(m==='POST'){if(t.created_by!==u.id)return B('Hanya Owner Akun yang dapat mengubah status publik.',403);const b=await body(request),on=!!b.is_public;let s=await env.DB.prepare('SELECT * FROM share_tokens WHERE tree_id=?').bind(t.id).first();if(!s){const tok=await uniqueShortToken(env);await env.DB.prepare('INSERT INTO share_tokens(tree_id,token,is_public) VALUES(?,?,?)').bind(t.id,tok,on?1:0).run();s={token:tok}}else{let tok=s.token;if(tok.length>12){tok=await uniqueShortToken(env);await env.DB.prepare('UPDATE share_tokens SET token=? WHERE tree_id=?').bind(tok,t.id).run()}await env.DB.prepare('UPDATE share_tokens SET is_public=?,updated_at=CURRENT_TIMESTAMP WHERE tree_id=?').bind(on?1:0,t.id).run();s={...s,token:tok}}return J({public:on,token:s.token,url:on?`${url.origin}/f/${s.token}`:null})}}
 const cl=path.match(/^\/trees\/(\d+)\/claims$/);if(cl){const t=await tree(env,Number(cl[1]));if(!t||t.created_by!==u.id)return B('Akses Owner Akun diperlukan.',403);if(m==='GET')return J({claims:(await env.DB.prepare(`SELECT c.*,p.first_name,p.last_name,u.name requester_name,u.email requester_email FROM claim_requests c JOIN persons p ON p.id=c.person_id JOIN users u ON u.id=c.requester_id WHERE c.tree_id=? ORDER BY c.created_at DESC`).bind(t.id).all()).results||[]});if(m==='POST'){const b=await body(request),c=await env.DB.prepare("SELECT * FROM claim_requests WHERE id=? AND tree_id=? AND status='pending'").bind(Number(b.claimId),t.id).first();if(!c)return B('Permintaan klaim tidak ditemukan.',404);if(b.action==='approve'){const plan=await planOf(env,u.id),cnt=await env.DB.prepare("SELECT COUNT(*) n FROM tree_members WHERE tree_id=? AND status='active'").bind(t.id).first();if(Number(cnt?.n)>=limits(plan).members)return B(`Batas Family Member paket ${plan} tercapai.`,409);await env.DB.prepare("INSERT OR REPLACE INTO tree_members(tree_id,user_id,person_id,status,updated_at) VALUES(?,?,?,'active',CURRENT_TIMESTAMP)").bind(t.id,c.requester_id,c.person_id).run();await env.DB.prepare("UPDATE claim_requests SET status='approved',reviewed_at=CURRENT_TIMESTAMP WHERE id=?").bind(c.id).run()}else await env.DB.prepare("UPDATE claim_requests SET status='rejected',reviewed_at=CURRENT_TIMESTAMP WHERE id=?").bind(c.id).run();return J({ok:true})}}
 const iv=path.match(/^\/trees\/(\d+)\/invites$/);if(iv){const t=await tree(env,Number(iv[1]));if(!t||t.created_by!==u.id)return B('Akses Owner Akun diperlukan.',403);if(m==='GET'){const r=await env.DB.prepare('SELECT i.*,p.first_name,p.last_name,u.name requester_name,u.email requester_email FROM invitations i JOIN persons p ON p.id=i.person_id LEFT JOIN users u ON u.id=i.requester_id WHERE i.tree_id=? ORDER BY i.created_at DESC').bind(t.id).all();return J({invites:r.results||[]})}if(m==='POST'){const b=await body(request),pid=Number(b.personId),e=mail(b.email),ph=clean(b.phone,40),p=await env.DB.prepare('SELECT id,first_name,last_name FROM persons WHERE id=? AND tree_id=?').bind(pid,t.id).first();if(!p||(!e.includes('@')&&!ph))return B('Pilih anggota dan isi email atau nomor WhatsApp.');const plan=await planOf(env,u.id),cnt=await env.DB.prepare("SELECT COUNT(*) n FROM tree_members WHERE tree_id=? AND status='active'").bind(t.id).first();if(Number(cnt?.n)>=limits(plan).members)return B(`Batas Family Member paket ${plan} tercapai.`,409);const tok=shortRand();await env.DB.prepare('INSERT INTO invitations(tree_id,person_id,invited_email,invited_phone,invited_by,token) VALUES(?,?,?,?,?,?)').bind(t.id,pid,e,ph,u.id,tok).run();return J({ok:true,inviteUrl:`${url.origin}/invite/${tok}`,token:tok,personName:pname(p),email:e,phone:ph})}}
 const ivd=path.match(/^\/trees\/(\d+)\/invites\/(\d+)$/);if(ivd&&m==='POST'){const t=await tree(env,Number(ivd[1]));if(!t||t.created_by!==u.id)return B('Akses Owner Akun diperlukan.',403);const b=await body(request),i=await env.DB.prepare("SELECT * FROM invitations WHERE id=? AND tree_id=? AND status='pending'").bind(Number(ivd[2]),t.id).first();if(!i)return B('Undangan tidak ditemukan atau sudah diproses.',404);if(!i.requester_id||!i.requested_at)return B('Calon Family Member belum mengajukan permintaan.',400);if(b.action==='approve'){const already=await env.DB.prepare("SELECT id FROM tree_members WHERE tree_id=? AND (user_id=? OR person_id=?) AND status='active'").bind(t.id,i.requester_id,i.person_id).first();if(already)return B('Anggota atau akun tersebut sudah menjadi Family Member.',409);const plan=await planOf(env,u.id),cnt=await env.DB.prepare("SELECT COUNT(*) n FROM tree_members WHERE tree_id=? AND status='active'").bind(t.id).first();if(Number(cnt?.n)>=limits(plan).members)return B(`Batas Family Member paket ${plan} tercapai.`,409);await env.DB.prepare("INSERT OR REPLACE INTO tree_members(tree_id,user_id,person_id,status,updated_at) VALUES(?,?,?,'active',CURRENT_TIMESTAMP)").bind(t.id,i.requester_id,i.person_id).run();await env.DB.prepare("UPDATE invitations SET status='accepted',responded_at=CURRENT_TIMESTAMP WHERE id=?").bind(i.id).run();return J({ok:true,message:'Family Member diterima.'})}if(b.action==='reject'){await env.DB.prepare("UPDATE invitations SET status='rejected',responded_at=CURRENT_TIMESTAMP WHERE id=?").bind(i.id).run();return J({ok:true,message:'Undangan ditolak.'})}return B('Aksi tidak valid.')}
 const ivdel=path.match(/^\/trees\/(\d+)\/invites\/(\d+)$/);if(ivdel&&m==='DELETE'){const t=await tree(env,Number(ivdel[1]));if(!t||t.created_by!==u.id)return B('Akses Owner Akun diperlukan.',403);const i=await env.DB.prepare("SELECT id FROM invitations WHERE id=? AND tree_id=?").bind(Number(ivdel[2]),t.id).first();if(!i)return B('Undangan tidak ditemukan.',404);await env.DB.prepare('DELETE FROM invitations WHERE id=?').bind(i.id).run();return J({ok:true,message:'Undangan dihapus.'})}
 const ia=path.match(/^\/invitations\/([A-Za-z0-9_-]+)$/);if(ia&&m==='POST'){const i=await env.DB.prepare("SELECT * FROM invitations WHERE token=? AND status='pending'").bind(ia[1]).first();if(!i)return B('Undangan tidak ditemukan atau sudah digunakan.',404);if(i.invited_email&&mail(u.email)!==mail(i.invited_email))return B('Undangan ditujukan untuk email lain.',403);const t=await tree(env,i.tree_id);if(!t)return B('Silsilah tidak ditemukan.',404);if(i.requested_at)return J({ok:true,message:'Permintaan sudah dikirim dan menunggu persetujuan Owner Akun.'});await env.DB.prepare('UPDATE invitations SET requester_id=?,requested_at=CURRENT_TIMESTAMP WHERE id=?').bind(u.id,i.id).run();return J({ok:true,message:'Permintaan bergabung dikirim. Tunggu persetujuan Owner Akun.'})}
 if(path==='/claims'&&m==='POST'){const b=await body(request),s=await env.DB.prepare('SELECT * FROM share_tokens WHERE token=? AND is_public=1').bind(clean(b.shareToken,200)).first();if(!s)return B('Link publik tidak valid.',404);const p=await env.DB.prepare('SELECT id FROM persons WHERE id=? AND tree_id=?').bind(Number(b.personId),s.tree_id).first();if(!p)return B('Anggota tidak ditemukan.',404);if((await tree(env,s.tree_id)).created_by===u.id)return B('Owner Akun tidak perlu mengklaim nama sendiri.');const x=await env.DB.prepare("SELECT id FROM claim_requests WHERE tree_id=? AND person_id=? AND requester_id=? AND status='pending'").bind(s.tree_id,p.id,u.id).first();if(x)return B('Klaim sudah diajukan.',409);await env.DB.prepare('INSERT INTO claim_requests(tree_id,person_id,requester_id,note) VALUES(?,?,?,?)').bind(s.tree_id,p.id,u.id,clean(b.note,1000)).run();return J({ok:true,message:'Permintaan klaim dikirim.'},201)}
 if(path==='/account/upgrade'&&m==='POST'){if(u.role!=='member')return B('Hanya akun Member yang dapat upgrade.',403);const plan=await planOf(env,u.id);if(plan==='ultimate')return B('Akun Anda sudah Ultimate.',409);const pending=await env.DB.prepare("SELECT id FROM payment_requests WHERE user_id=? AND status='pending' AND note LIKE 'Upgrade Premium%ultimate%' LIMIT 1").bind(u.id).first();if(pending)return B('Permintaan upgrade masih menunggu verifikasi Owner Web.',409);const amt=Math.round(price('ultimate',env)*0.6);await env.DB.prepare("INSERT INTO payment_requests(user_id,amount,status,note) VALUES(?,?, 'pending',?)").bind(u.id,amt,'Upgrade Premium ke Ultimate (diskon 40%)').run();return J({ok:true,amount:amt,message:'Permintaan upgrade dikirim. Lakukan pembayaran sesuai instruksi dan tunggu verifikasi Owner Web.'},201)}
 if(path==='/my/invitations'&&m==='GET')return J({invites:(await env.DB.prepare("SELECT i.*,t.name tree_name,p.first_name,p.last_name FROM invitations i JOIN family_trees t ON t.id=i.tree_id JOIN persons p ON p.id=i.person_id WHERE i.invited_email=? AND i.status='pending' ORDER BY i.created_at DESC").bind(u.email).all()).results||[]});
 if(path==='/my/memberships'&&m==='GET')return J({memberships:(await env.DB.prepare("SELECT tm.*,t.name tree_name,p.first_name,p.last_name FROM tree_members tm JOIN family_trees t ON t.id=tm.tree_id JOIN persons p ON p.id=tm.person_id WHERE tm.user_id=? AND tm.status='active'").bind(u.id).all()).results||[]});
 if(path==='/my/claims'&&m==='GET')return J({claims:(await env.DB.prepare('SELECT c.*,t.name tree_name,p.first_name,p.last_name FROM claim_requests c JOIN family_trees t ON t.id=c.tree_id JOIN persons p ON p.id=c.person_id WHERE c.requester_id=? ORDER BY c.created_at DESC').bind(u.id).all()).results||[]});
 if(path==='/trees/audit'&&m==='GET')return B('Gunakan URL audit per silsilah.',400);
 const au=path.match(/^\/trees\/(\d+)\/audit$/);if(au&&m==='GET'){const t=await tree(env,Number(au[1]));if(!t||u.role!=='member'||t.created_by!==u.id)return B('Akses Owner Akun diperlukan.',403);return J({logs:(await env.DB.prepare('SELECT a.*,u.name actor_name FROM audit_logs a JOIN users u ON u.id=a.actor_user_id WHERE a.tree_id=? ORDER BY a.created_at DESC LIMIT 200').bind(t.id).all()).results||[]})}
 return B('Endpoint tidak ditemukan.',404);
}
